version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
sphinx:
  configuration: doc/ref_arch/openstack/conf.py
python:
  install:
    - requirements: doc/ref_arch/openstack/test-requirements.txt
